# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArazzoMcpGen < Formula
  desc "A CLI tool to generate MCP servers from Arazzo specifications."
  homepage "https://github.com/HimethW/arazzo-mcp-gen"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HimethW/arazzo-mcp-gen/releases/download/v0.1.1/arazzo-mcp-gen_Darwin_x86_64.tar.gz"
      sha256 "6ae75acff3a7541d45b05a3727514096b7f95887719f22a3a99135a609ebd5b4"

      define_method(:install) do
        bin.install "arazzo-mcp-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HimethW/arazzo-mcp-gen/releases/download/v0.1.1/arazzo-mcp-gen_Darwin_arm64.tar.gz"
      sha256 "a320ad77a57362d4af1f507ee7acb25c867783c9dd251057fcfdb22c24913932"

      define_method(:install) do
        bin.install "arazzo-mcp-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HimethW/arazzo-mcp-gen/releases/download/v0.1.1/arazzo-mcp-gen_Linux_x86_64.tar.gz"
      sha256 "f70e5224a7c8d0ae1eb5cdcadc2f278d22fb7119f0b382a057f879b253e466a6"
      define_method(:install) do
        bin.install "arazzo-mcp-gen"
      end
    end
  end

  test do
    system "#{bin}/arazzo-mcp-gen", "--version"
  end
end
