# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArazzoMcpGen < Formula
  desc "A CLI tool to generate MCP servers from Arazzo specifications."
  homepage "https://github.com/HimethW/arazzo-mcp-gen"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HimethW/arazzo-mcp-gen/releases/download/v0.1.6/arazzo-mcp-gen_Darwin_x86_64.tar.gz"
      sha256 "e50d56e3a43a04a56af5d814c04bfa222845a67b946f2fcd8c64f309847f64c2"

      define_method(:install) do
        bin.install "arazzo-mcp-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HimethW/arazzo-mcp-gen/releases/download/v0.1.6/arazzo-mcp-gen_Darwin_arm64.tar.gz"
      sha256 "e5f01129f1febdaa8e0e0c402fb2aab6ace8bab2bfd6c03e87ca98aaf7e8948d"

      define_method(:install) do
        bin.install "arazzo-mcp-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HimethW/arazzo-mcp-gen/releases/download/v0.1.6/arazzo-mcp-gen_Linux_x86_64.tar.gz"
      sha256 "7367f853488607b7e1f1eb24b48987514c24066a4b32fdba96116c0c5f99f1ec"
      define_method(:install) do
        bin.install "arazzo-mcp-gen"
      end
    end
  end

  test do
    system "#{bin}/arazzo-mcp-gen", "--version"
  end
end
